<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="SuiteName" duration-ms="4438" started-at="2017-04-24T12:19:19Z" finished-at="2017-04-24T12:19:23Z">
    <groups>
    </groups>
    <test name="Login Test" duration-ms="4438" started-at="2017-04-24T12:19:19Z" finished-at="2017-04-24T12:19:23Z">
      <class name="com.unisys.pom.testcases.LoginTest">
        <test-method status="FAIL" signature="doLogin(java.util.Hashtable)[pri:0, instance:com.unisys.pom.testcases.LoginTest@245b4bdc]" name="doLogin" duration-ms="4097" started-at="2017-04-24T17:49:19Z" data-provider="getData" finished-at="2017-04-24T17:49:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=9538442585, ExpectedResult=Success, Password=Unisys*1234, Runmode=Y, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.unisys.pom.testcases.base.BaseTest.init(BaseTest.java:86)
	at com.unisys.pom.testcases.LoginTest.doLogin(LoginTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.unisys.pom.testcases.LoginTest@245b4bdc]" name="quit" is-config="true" duration-ms="296" started-at="2017-04-24T17:49:23Z" finished-at="2017-04-24T17:49:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.unisys.pom.testcases.LoginTest -->
    </test> <!-- Login Test -->
  </suite> <!-- SuiteName -->
</testng-results>
